import { describe, expect, it } from 'vitest';
import { assignCombinedLogos, buildCombinedReplacementPrompt, combinedTaskCount, type CombinedLogoProfile, type CombinedSceneAnalysis } from './combinedReplace';
const scene = (id: string, count: number): CombinedSceneAnalysis => ({ sceneId: id, summary: '', subject: '', composition: '', camera: '', lighting: '', individualPrompt: '', styles: Array.from({ length: count }, (_, i) => ({ id: `${id}-${i}`, label: `样式 ${i + 1}`, description: i ? '圆形金色' : '方形黑色', occurrences: i + 1, carrier: i ? '玻璃杯' : '木盒' })) });
const logos: CombinedLogoProfile[] = [{ logoId: 'a', summary: '黑色方形', style: '简约', colors: '黑', suitableFor: ['木盒'] }, { logoId: 'b', summary: '粉色圆形', style: '柔和', colors: '粉', suitableFor: ['服装'] }, { logoId: 'c', summary: '金色圆形', style: '精致', colors: '金', suitableFor: ['玻璃杯'] }];
describe('combined replace helpers', () => {
  it('uses different logos for styles in one scene and permits cross-scene reuse', () => { const result = assignCombinedLogos([scene('s1', 2), scene('s2', 2)], logos.slice(0, 2), true); expect(result.error).toBeUndefined(); expect(new Set(result.plans[0].mappings.map((m) => m.logoId)).size).toBe(2); expect(result.plans[1].mappings).toHaveLength(2); });
  it('blocks shortages with and without reuse', () => { expect(assignCombinedLogos([scene('s', 2)], logos.slice(0, 1), true).error).toContain('单张场景'); expect(assignCombinedLogos([scene('a', 2), scene('b', 2)], logos.slice(0, 3), false).error).toContain('全部场景'); });
  it('marks unmatched choices random', () => { const result = assignCombinedLogos([scene('s', 1)], [{ logoId: 'x', summary: '无关', style: '', colors: '', suitableFor: [] }], true); expect(result.plans[0].mappings[0].source).toBe('random'); });
  it('builds ordered prompt and task count', () => { const s = scene('s', 1); const prompt = buildCombinedReplacementPrompt({ scenePrompt: '海边', logoPrompt: '雕刻', individualPrompt: '暖光', styles: s.styles, mappings: [{ styleId: 's-0', logoId: 'a', source: 'matched', reason: '' }], logoOrder: ['a'] }); expect(prompt).toContain('第 2 张'); expect(prompt).toContain('手势严格不变'); expect(combinedTaskCount(3, 2)).toBe(6); });
});
