import { App, Alert, Button, Card, Empty, Flex, Input, InputNumber, Progress, Space, Statistic, Tag, Typography, Upload } from 'antd';
import { DownloadOutlined, FolderOpenOutlined, RocketOutlined } from '@ant-design/icons';
import JSZip from 'jszip';
import { useCallback, useEffect, useRef, useState } from 'react';
import SceneReplaceComposer from './SceneReplaceComposer';
import { groupFolderFiles } from './MultiTabLogoReplaceComposer';
import type { SceneReplaceTask } from './types';
import { downloadBlob, formatFileTimestamp, mimeExtension, sanitizeFileName } from './utils';

const { Title, Text, Paragraph } = Typography;
const DB_NAME = 'scene-studio.multi-tab-scene-replace.v1'; const STORE = 'batches';
type Group = ReturnType<typeof groupFolderFiles>[number];
interface Batch { id: string; groups: Group[]; prompt: string; concurrency: number; startToken?: string }
interface ProgressState { total: number; completed: number; failed: number; running: boolean }
function db() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE, { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function save(batch: Batch) { const store = await db(); await new Promise<void>((resolve, reject) => { const tx = store.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put(batch); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); store.close(); }
async function read(id: string) { const store = await db(); const value = await new Promise<Batch | undefined>((resolve, reject) => { const request = store.transaction(STORE).objectStore(STORE).get(id); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); store.close(); return value; }
function inject(input: HTMLInputElement | null, files: File[]) { if (!input) return; const transfer = new DataTransfer(); files.forEach((file) => transfer.items.add(file)); input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true })); }

export default function MultiTabSceneReplaceComposer(props: Parameters<typeof SceneReplaceComposer>[0]) {
  const { message } = App.useApp(); const params = new URLSearchParams(location.search); const worker = params.get('worker') === '1'; const batchId = params.get('batch'); const groupId = params.get('group');
  const [groups, setGroups] = useState<Group[]>([]); const [prompt, setPrompt] = useState(''); const [concurrency, setConcurrency] = useState(6); const [activeBatch, setActiveBatch] = useState<string>();
  const [workerBatch, setWorkerBatch] = useState<Batch>(); const [workerGroup, setWorkerGroup] = useState<Group>(); const [injected, setInjected] = useState(false); const [startToken, setStartToken] = useState<string>();
  const [progress, setProgress] = useState<Record<string, ProgressState>>({}); const [results, setResults] = useState<Record<string, SceneReplaceTask[]>>({}); const root = useRef<HTMLDivElement>(null); const channel = useRef<BroadcastChannel | undefined>(undefined);
  useEffect(() => { channel.current = new BroadcastChannel('scene-studio-scene-tabs'); const receive = (event: MessageEvent) => { const data = event.data; if (worker && data.batchId === batchId && data.type === 'start') setStartToken(data.token); if (!worker && data.batchId === activeBatch && data.type === 'progress') setProgress((current) => ({ ...current, [data.groupId]: data.progress })); if (!worker && data.batchId === activeBatch && data.type === 'results') setResults((current) => ({ ...current, [data.groupId]: data.tasks })); }; channel.current.addEventListener('message', receive); return () => channel.current?.close(); }, [worker, batchId, activeBatch]);
  useEffect(() => { if (!worker || !batchId || !groupId) return; void read(batchId).then((batch) => { setWorkerBatch(batch); setWorkerGroup(batch?.groups.find((group) => group.id === groupId)); setStartToken(batch?.startToken); }); }, [worker, batchId, groupId]);
  useEffect(() => { if (!worker || !workerBatch?.concurrency || !navigator.locks) return; const originalFetch = window.fetch.bind(window); window.fetch = async (...args) => { const target = typeof args[0] === 'string' ? args[0] : args[0] instanceof URL ? args[0].href : args[0].url; if (!/generativelanguage\.googleapis\.com|api\.openai\.com|\/api\/gemini/i.test(target)) return originalFetch(...args); while (true) { for (let index = 0; index < workerBatch.concurrency; index += 1) { const result = await navigator.locks.request(`scene-studio-scene-ai-slot-${index}`, { ifAvailable: true }, async (lock) => lock ? originalFetch(...args) : undefined); if (result) return result; } await new Promise((resolve) => window.setTimeout(resolve, 120)); } }; return () => { window.fetch = originalFetch; }; }, [worker, workerBatch?.concurrency]);
  useEffect(() => { if (!workerGroup || injected) return; const timer = window.setTimeout(() => { inject(root.current?.querySelector('input[type="file"]') || null, workerGroup.files); setInjected(true); }, 500); return () => clearTimeout(timer); }, [workerGroup, injected]);
  const open = async (only?: Group) => { if (!groups.length || !prompt.trim()) return void message.warning('请选择场景文件夹并填写公共提示词'); const selected = only ? [only] : groups; const id = activeBatch || `scene-batch-${Date.now()}`; const windows = selected.map((group) => window.open('', `scene-worker-${id}-${group.id}-${Date.now()}`)); await save({ id, groups, prompt: prompt.trim(), concurrency }); setActiveBatch(id); selected.forEach((group, index) => { const url = new URL(location.href); url.searchParams.set('tool', 'scene-replace-tabs'); url.searchParams.set('worker', '1'); url.searchParams.set('batch', id); url.searchParams.set('group', group.id); url.searchParams.set('folder', group.name); if (windows[index]) windows[index]!.location.href = url.toString(); }); };
  const startAll = async () => { if (!activeBatch) return void message.warning('请先打开工作标签'); const batch = await read(activeBatch); if (!batch) return; const token = `start-${Date.now()}`; batch.startToken = token; await save(batch); channel.current?.postMessage({ type: 'start', batchId: activeBatch, token }); };
  const downloadable = Object.values(results).flatMap((tasks) => tasks.filter((task) => task.resultBlob));
  const reportWorkerProgress = useCallback((value: ProgressState) => channel.current?.postMessage({ type: 'progress', batchId, groupId, progress: value }), [batchId, groupId]);
  const reportWorkerResults = useCallback((tasks: SceneReplaceTask[]) => channel.current?.postMessage({ type: 'results', batchId, groupId, tasks }), [batchId, groupId]);
  const downloadAll = async () => { const zip = new JSZip(); Object.entries(results).forEach(([id, tasks]) => { const folder = zip.folder(sanitizeFileName(groups.find((group) => group.id === id)?.name || id)); tasks.filter((task) => task.resultBlob).forEach((task) => { folder?.file(`${task.sceneIndex + 1}_${task.copyIndex + 1}.${mimeExtension(task.resultMimeType)}`, task.resultBlob!); task.outpaintResults?.forEach((item) => folder?.file(`${task.sceneIndex + 1}_${task.copyIndex + 1}_扩图_${item.width}x${item.height}.png`, item.blob)); }); }); downloadBlob(await zip.generateAsync({ type: 'blob' }), `SceneStudio_多标签场景替换_${formatFileTimestamp()}.zip`); };
  if (worker) return <div ref={root}><Alert type={injected ? 'success' : 'info'} showIcon title={workerGroup ? `场景工作标签：${workerGroup.name}` : '正在加载分组'} description={injected ? `已导入 ${workerGroup?.files.length || 0} 张图片和公共提示词` : '正在自动导入'} style={{ marginBottom: 16 }} /><SceneReplaceComposer {...props} initialPrompt={workerBatch?.prompt} automationStartToken={startToken} onProgressChange={reportWorkerProgress} onResultsChange={reportWorkerResults} /></div>;
  const totals = Object.values(progress).reduce((sum, item) => ({ total: sum.total + item.total, completed: sum.completed + item.completed, failed: sum.failed + item.failed }), { total: 0, completed: 0, failed: 0 });
  return <div className="multi-tab-logo-page"><section className="hero-strip scene-replace-hero"><div><Text className="eyebrow">MULTI-TAB SCENE REPLACER</Text><Title level={2}>一个主控页，分发多组场景替换任务</Title><Paragraph>按最深层图片目录分组，共用提示词与本地场景替换设置，并在独立标签中并行执行。</Paragraph></div><div className="hero-orb" /></section>
    <Card title="1. 选择场景根文件夹"><Upload.Dragger directory multiple showUploadList={false} accept="image/png,image/jpeg,image/webp" beforeUpload={(file, list) => { if (file.uid === list.at(-1)?.uid) setGroups(groupFolderFiles(list as File[])); return Upload.LIST_IGNORE; }}><FolderOpenOutlined style={{ fontSize: 34 }} /><p>拖拽或点击选择场景根文件夹</p></Upload.Dragger>{groups.length ? <div className="folder-group-grid">{groups.map((group) => <Card key={group.id} size="small" title={group.name}><Text type="secondary">{group.path} · {group.files.length} 张</Text><Button block type="link" onClick={() => void open(group)}>单独打开标签</Button></Card>)}</div> : <Empty description="选择文件夹后显示分组" />}</Card>
    <Card title="2. 公共场景替换提示词"><Input.TextArea value={prompt} onChange={(event) => setPrompt(event.target.value)} autoSize={{ minRows: 5, maxRows: 12 }} placeholder="输入发送给所有工作标签的完整场景替换提示词" /></Card>
    <Card className="action-card"><Flex justify="space-between" wrap gap={12}><div><Title level={4}>准备分发 {groups.length} 组</Title><Text type="secondary">所有标签共用浏览器本地保存的场景替换模型与扩图设置</Text></div><Space wrap><Text>全局并发</Text><InputNumber min={1} max={12} value={concurrency} onChange={(value) => setConcurrency(value || 1)} /><Button icon={<RocketOutlined />} onClick={() => void open()}>保存批次并打开全部标签</Button><Button type="primary" disabled={!activeBatch} onClick={startAll}>一键开始所有替换</Button><Button icon={<DownloadOutlined />} disabled={!downloadable.length} onClick={() => void downloadAll()}>下载全部（{downloadable.length}）</Button></Space></Flex>{totals.total > 0 && <><Flex gap={24}><Statistic title="任务总数" value={totals.total} /><Statistic title="已完成" value={totals.completed} /><Statistic title="失败" value={totals.failed} /></Flex><Progress percent={Math.round(totals.completed / totals.total * 100)} /></>}</Card>
  </div>;
}
