import { App, Alert, Button, Card, Checkbox, Collapse, Empty, Flex, Image, Input, InputNumber, Modal, Popconfirm, Progress, Space, Statistic, Switch, Tag, Typography, Upload } from 'antd';
import { DeleteOutlined, DownloadOutlined, FolderOpenOutlined, PlusOutlined, ReloadOutlined, RocketOutlined, StopOutlined } from '@ant-design/icons';
import JSZip from 'jszip';
import { useCallback, useEffect, useRef, useState } from 'react';
import type * as React from 'react';
import SceneReplaceComposer from './SceneReplaceComposer';
import { FileThumbnail, groupFolderFiles } from './MultiTabLogoReplaceComposer';
import type { SceneReplaceSettings, SceneReplaceTask } from './types';
import { downloadBlob, formatFileTimestamp, mimeExtension, sanitizeFileName } from './utils';
import { DEFAULT_SCENE_REPLACE_SETTINGS, STORAGE_KEYS } from './constants';
import { readLocalStorage } from './storage';
import { SCENE_COMMON_CONSTRAINT } from './services/sceneThemeRecommendation';

const { Title, Text, Paragraph } = Typography;
const DB_NAME = 'scene-studio.multi-tab-scene-replace.v1'; const STORE = 'batches';
type Group = ReturnType<typeof groupFolderFiles>[number];
interface PickerFolderNode { name: string; path: string; children: PickerFolderNode[]; group?: Group }
export function buildPickerFolderTree(groups: Group[]): PickerFolderNode[] {
  const leafGroups = groups.filter((group) => !groups.some((candidate) => candidate.path !== group.path && candidate.path.startsWith(`${group.path}/`)));
  const roots: PickerFolderNode[] = [];
  leafGroups.forEach((group) => { let nodes = roots; let path = ''; group.path.split('/').filter(Boolean).forEach((name, index, parts) => { path = path ? `${path}/${name}` : name; let node = nodes.find((item) => item.path === path); if (!node) { node = { name, path, children: [] }; nodes.push(node); } if (index === parts.length - 1) node.group = group; nodes = node.children; }); });
  return roots;
}
interface Batch { id: string; groups: Group[]; prompt: string; concurrency: number; startToken?: string }
interface ProgressState { total: number; completed: number; failed: number; running: boolean }
function LeafImage({ file }: { file: File }) { const [url, setUrl] = useState(''); useEffect(() => { const next = URL.createObjectURL(file); setUrl(next); return () => URL.revokeObjectURL(next); }, [file]); return url ? <Image src={url} alt={file.name} width={42} height={42} style={{ objectFit: 'cover', borderRadius: 5 }} /> : null; }
function db() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE, { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function save(batch: Batch) { const store = await db(); await new Promise<void>((resolve, reject) => { const tx = store.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put(batch); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); store.close(); }
async function read(id: string) { const store = await db(); const value = await new Promise<Batch | undefined>((resolve, reject) => { const request = store.transaction(STORE).objectStore(STORE).get(id); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); store.close(); return value; }
function inject(input: HTMLInputElement | null, files: File[]) { if (!input) return; const transfer = new DataTransfer(); files.forEach((file) => transfer.items.add(file)); input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true })); }

export default function MultiTabSceneReplaceComposer(props: Parameters<typeof SceneReplaceComposer>[0]) {
  const { message } = App.useApp(); const params = new URLSearchParams(location.search); const worker = params.get('worker') === '1'; const batchId = params.get('batch'); const groupId = params.get('group');
  const [groups, setGroups] = useState<Group[]>([]); const [prompt, setPrompt] = useState(''); const [concurrency, setConcurrency] = useState(6); const [activeBatch, setActiveBatch] = useState<string>();
  const [autoRecommendScene, setAutoRecommendScene] = useState(() => readLocalStorage<SceneReplaceSettings>(STORAGE_KEYS.sceneReplaceSettings, DEFAULT_SCENE_REPLACE_SETTINGS as SceneReplaceSettings).autoRecommendScene);
  const [workerBatch, setWorkerBatch] = useState<Batch>(); const [workerGroup, setWorkerGroup] = useState<Group>(); const [injected, setInjected] = useState(false); const [startToken, setStartToken] = useState<string>(); const [retryFailedToken, setRetryFailedToken] = useState<string>(); const [stopToken, setStopToken] = useState<string>();
  const [progress, setProgress] = useState<Record<string, ProgressState>>({}); const [results, setResults] = useState<Record<string, SceneReplaceTask[]>>({}); const root = useRef<HTMLDivElement>(null); const channel = useRef<BroadcastChannel | undefined>(undefined);
  const [pendingFolderFiles, setPendingFolderFiles] = useState<File[]>([]); const [checkedFolderKeys, setCheckedFolderKeys] = useState<string[]>([]); const [selectedGroupId, setSelectedGroupId] = useState<string>();
  const queuedGroups = useRef<string[]>([]); const activeGroups = useRef(new Set<string>()); const schedulingBatch = useRef<string | undefined>(undefined);
  const launchNextGroups = useCallback((targetBatch?: string) => { if (!targetBatch) return; while (activeGroups.current.size < concurrency && queuedGroups.current.length) { const targetGroupId = queuedGroups.current.shift()!; activeGroups.current.add(targetGroupId); channel.current?.postMessage({ type: 'start', batchId: targetBatch, groupId: targetGroupId, token: `start-${targetGroupId}-${Date.now()}` }); } }, [concurrency]);
  useEffect(() => { channel.current = new BroadcastChannel('scene-studio-scene-tabs'); const receive = (event: MessageEvent) => { const data = event.data; if (worker && data.batchId === batchId && data.type === 'start' && (!data.groupId || data.groupId === groupId)) setStartToken(data.token); if (worker && data.batchId === batchId && data.type === 'retry-failed') setRetryFailedToken(data.token); if (worker && data.batchId === batchId && data.type === 'stop-all') setStopToken(data.token); if (!worker && data.batchId === activeBatch && data.type === 'progress') { setProgress((current) => ({ ...current, [data.groupId]: data.progress })); if (schedulingBatch.current === activeBatch && data.progress.total > 0 && !data.progress.running && data.progress.completed >= data.progress.total) { activeGroups.current.delete(data.groupId); launchNextGroups(activeBatch); } } if (!worker && data.batchId === activeBatch && data.type === 'results') setResults((current) => ({ ...current, [data.groupId]: data.tasks })); }; channel.current.addEventListener('message', receive); return () => channel.current?.close(); }, [worker, batchId, groupId, activeBatch, launchNextGroups]);
  useEffect(() => { if (!worker || !batchId || !groupId) return; void read(batchId).then((batch) => { setWorkerBatch(batch); setWorkerGroup(batch?.groups.find((group) => group.id === groupId)); setStartToken(batch?.startToken); }); }, [worker, batchId, groupId]);
  useEffect(() => { if (!worker || !workerBatch?.concurrency || !navigator.locks) return; const originalFetch = window.fetch.bind(window); window.fetch = async (...args) => { const target = typeof args[0] === 'string' ? args[0] : args[0] instanceof URL ? args[0].href : args[0].url; if (!/generativelanguage\.googleapis\.com|api\.openai\.com|\/api\/gemini/i.test(target)) return originalFetch(...args); while (true) { for (let index = 0; index < workerBatch.concurrency; index += 1) { const result = await navigator.locks.request(`scene-studio-scene-ai-slot-${index}`, { ifAvailable: true }, async (lock) => lock ? originalFetch(...args) : undefined); if (result) return result; } await new Promise((resolve) => window.setTimeout(resolve, 120)); } }; return () => { window.fetch = originalFetch; }; }, [worker, workerBatch?.concurrency]);
  useEffect(() => { if (!workerGroup || injected) return; const timer = window.setTimeout(() => { inject(root.current?.querySelector('input[type="file"]') || null, workerGroup.files); setInjected(true); }, 500); return () => clearTimeout(timer); }, [workerGroup, injected]);
  const open = async (only?: Group) => { if (!groups.length || !prompt.trim()) return void message.warning('请选择场景文件夹并填写公共提示词'); const stored = readLocalStorage<SceneReplaceSettings>(STORAGE_KEYS.sceneReplaceSettings, DEFAULT_SCENE_REPLACE_SETTINGS as SceneReplaceSettings); localStorage.setItem(STORAGE_KEYS.sceneReplaceSettings, JSON.stringify({ ...stored, autoRecommendScene })); const selected = only ? [only] : groups; const id = activeBatch || `scene-batch-${Date.now()}`; const windows = selected.map((group) => window.open('', `scene-worker-${id}-${group.id}-${Date.now()}`)); await save({ id, groups, prompt: prompt.trim(), concurrency }); setActiveBatch(id); selected.forEach((group, index) => { const url = new URL(location.href); url.searchParams.set('tool', 'scene-replace-tabs'); url.searchParams.set('worker', '1'); url.searchParams.set('batch', id); url.searchParams.set('group', group.id); url.searchParams.set('folder', group.name); if (windows[index]) windows[index]!.location.href = url.toString(); }); };
  const startAll = async () => { if (!activeBatch) return void message.warning('请先打开工作标签'); const batch = await read(activeBatch); if (!batch) return; delete batch.startToken; batch.concurrency = concurrency; await save(batch); schedulingBatch.current = activeBatch; activeGroups.current.clear(); queuedGroups.current = batch.groups.map((group) => group.id); setProgress({}); launchNextGroups(activeBatch); message.success(`已按主控并发 ${concurrency} 启动分组队列`); };
  const retryAllFailed = () => { if (!activeBatch || !totals.failed) return; channel.current?.postMessage({ type: 'retry-failed', batchId: activeBatch, token: `retry-${Date.now()}` }); message.success('已通知所有工作标签重试失败任务'); };
  const stopAll = () => { if (!activeBatch) return; queuedGroups.current = []; activeGroups.current.clear(); schedulingBatch.current = undefined; channel.current?.postMessage({ type: 'stop-all', batchId: activeBatch, token: `stop-${Date.now()}` }); message.info('已停止队列，并通知所有工作标签停止任务'); };
  const disableCloseWarnings = () => { channel.current?.postMessage({ type: 'disable-close-warning', batchId: activeBatch }); message.success('已通知所有工作标签关闭离页提醒'); };
  const downloadable = Object.values(results).flatMap((tasks) => tasks.filter((task) => task.resultBlob));
  const reportWorkerProgress = useCallback((value: ProgressState) => channel.current?.postMessage({ type: 'progress', batchId, groupId, progress: value }), [batchId, groupId]);
  const reportWorkerResults = useCallback((tasks: SceneReplaceTask[]) => channel.current?.postMessage({ type: 'results', batchId, groupId, tasks }), [batchId, groupId]);
  const reviewFolderFiles = (files: File[]) => {
    const accepted = files.filter((file) => ['image/png', 'image/jpeg', 'image/webp'].includes(file.type));
    const leafGroups = buildPickerFolderTree(groupFolderFiles(accepted)); const leafPaths: string[] = []; const collect = (nodes: PickerFolderNode[]) => nodes.forEach((node) => { if (node.group) leafPaths.push(`dir:${node.path}`); collect(node.children); }); collect(leafGroups);
    setPendingFolderFiles(accepted); setCheckedFolderKeys(leafPaths);
  };
  const importCheckedFolderFiles = () => {
    const pendingGroups = groupFolderFiles(pendingFolderFiles); const next = pendingGroups.filter((group) => checkedFolderKeys.includes(`dir:${group.path}`)); const selectedCount = next.reduce((sum, group) => sum + group.files.length, 0);
    setGroups(next); setPendingFolderFiles([]); setCheckedFolderKeys([]); message.success(`已导入 ${selectedCount} 张图片，共 ${next.length} 个分组`);
  };
  const downloadAll = async () => { const zip = new JSZip(); Object.entries(results).forEach(([id, tasks]) => { const folder = zip.folder(sanitizeFileName(groups.find((group) => group.id === id)?.name || id)); tasks.filter((task) => task.resultBlob).forEach((task) => { folder?.file(`${task.sceneIndex + 1}_${task.copyIndex + 1}.${mimeExtension(task.resultMimeType)}`, task.resultBlob!); task.outpaintResults?.forEach((item) => folder?.file(`${task.sceneIndex + 1}_${task.copyIndex + 1}_扩图_${item.width}x${item.height}.png`, item.blob)); }); }); downloadBlob(await zip.generateAsync({ type: 'blob' }), `SceneStudio_多标签场景替换_${formatFileTimestamp()}.zip`); };
  if (worker) return <div ref={root}><Alert type={injected ? 'success' : 'info'} showIcon title={workerGroup ? `场景工作标签：${workerGroup.name}` : '正在加载分组'} description={injected ? `已导入 ${workerGroup?.files.length || 0} 张图片和公共提示词` : '正在自动导入'} style={{ marginBottom: 16 }} /><SceneReplaceComposer {...props} initialPrompt={workerBatch?.prompt} automationStartToken={startToken} automationRetryFailedToken={retryFailedToken} automationStopToken={stopToken} onProgressChange={reportWorkerProgress} onResultsChange={reportWorkerResults} /></div>;
  const totals = Object.values(progress).reduce((sum, item) => ({ total: sum.total + item.total, completed: sum.completed + item.completed, failed: sum.failed + item.failed }), { total: 0, completed: 0, failed: 0 });
  const pendingGroups = groupFolderFiles(pendingFolderFiles); const pendingTree = buildPickerFolderTree(pendingGroups); const selectedGroup = groups.find((group) => group.id === selectedGroupId);
  const leafFolderKeys: string[] = []; const collectLeafKeys = (nodes: PickerFolderNode[]) => nodes.forEach((node) => { if (node.group) leafFolderKeys.push(`dir:${node.path}`); collectLeafKeys(node.children); }); collectLeafKeys(pendingTree);
  const levelEmoji = (depth: number) => `${Math.min(depth + 1, 9)}\uFE0F\u20E3`;
  const toggleFolder = (key: string) => setCheckedFolderKeys((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const renderPickerTree = (nodes: PickerFolderNode[], depth = 0): React.ReactNode => <Collapse size="small" bordered={false} defaultActiveKey={nodes.map((node) => node.path)} items={nodes.map((node) => { const key = `dir:${node.path}`; const checked = checkedFolderKeys.includes(key); return { key: node.path, label: <Flex align="center" gap={8}><span aria-label={`第 ${depth + 1} 层`}>{levelEmoji(depth)}</span><FolderOpenOutlined /><Text strong={Boolean(node.group)}>{node.name}</Text>{node.group && <Tag>{node.group.files.length} 张</Tag>}</Flex>, children: <><>{node.group && <Card size="small" hoverable className={checked ? 'scene-leaf-folder-card is-selected' : 'scene-leaf-folder-card'} onClick={() => toggleFolder(key)}><Checkbox checked={checked} onClick={(event) => event.stopPropagation()} onChange={() => toggleFolder(key)}>导入此文件夹</Checkbox><div onClick={(event) => event.stopPropagation()}><Image.PreviewGroup><Flex gap={4} wrap className="scene-folder-mini-thumbnails">{node.group.files.slice(0, 12).map((file, index) => <LeafImage file={file} key={`${file.name}-${index}`} />)}</Flex></Image.PreviewGroup></div>{node.group.files.length > 12 && <Text type="secondary">另有 {node.group.files.length - 12} 张</Text>}</Card>}</>{node.children.length ? renderPickerTree(node.children, depth + 1) : null}</> }; })} />;
  const removeGroup = (id: string) => { setGroups((current) => current.filter((group) => group.id !== id)); setSelectedGroupId((current) => current === id ? undefined : current); };
  const removeGroupFile = (groupId: string, target: File) => setGroups((current) => current.flatMap((group) => { if (group.id !== groupId) return [group]; const files = group.files.filter((file) => file !== target); return files.length ? [{ ...group, files }] : []; }));
  const addGroupFile = (groupId: string, file: File) => { if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type)) { message.error(`${file.name} 不是支持的图片格式`); return Upload.LIST_IGNORE; } setGroups((current) => current.map((group) => group.id === groupId ? { ...group, files: [...group.files, file] } : group)); return Upload.LIST_IGNORE; };
  return <div className="multi-tab-logo-page"><section className="hero-strip scene-replace-hero"><div><Text className="eyebrow">MULTI-TAB SCENE REPLACER</Text><Title level={2}>一个主控页，分发多组场景替换任务</Title><Paragraph>按最深层图片目录分组，共用提示词与本地场景替换设置，并在独立标签中并行执行。</Paragraph></div><div className="hero-orb" /></section>
    <Card title="1. 选择场景根文件夹"><Upload.Dragger directory multiple showUploadList={false} accept="image/png,image/jpeg,image/webp" beforeUpload={(file, list) => { if (file.uid === list.at(-1)?.uid) reviewFolderFiles(list as File[]); return Upload.LIST_IGNORE; }}><FolderOpenOutlined style={{ fontSize: 34 }} /><p>拖拽或点击选择场景根文件夹</p></Upload.Dragger>{groups.length ? <div className="folder-group-grid">{groups.map((group) => <Card key={group.id} size="small" hoverable title={group.name} onClick={() => setSelectedGroupId(group.id)}><Text type="secondary">{group.path} · {group.files.length} 张</Text><Flex gap={6} wrap><Button type="link" size="small" onClick={(event) => { event.stopPropagation(); setSelectedGroupId(group.id); }}>管理图片</Button><Button type="link" size="small" onClick={(event) => { event.stopPropagation(); void open(group); }}>单独打开标签</Button><Popconfirm title={`移除分组 ${group.name}？`} onConfirm={() => removeGroup(group.id)}><Button danger type="link" size="small" icon={<DeleteOutlined />} onClick={(event) => event.stopPropagation()}>移除</Button></Popconfirm></Flex></Card>)}</div> : <Empty description="选择文件夹后显示分组" />}</Card>
    <Card title="2. 公共场景替换提示词"><Flex justify="space-between" align="center" style={{ marginBottom: 12 }}><Text strong>上传后自动推荐非节日场景</Text><Switch checked={autoRecommendScene} onChange={(value) => { setAutoRecommendScene(value); if (value && !prompt.trim()) setPrompt(SCENE_COMMON_CONSTRAINT); }} /></Flex><Input.TextArea value={prompt} onChange={(event) => setPrompt(event.target.value)} autoSize={{ minRows: 5, maxRows: 12 }} placeholder="输入发送给所有工作标签的完整场景替换提示词" /></Card>
    <Card className="action-card"><Flex justify="space-between" wrap gap={12}><div><Title level={4}>准备分发 {groups.length} 组</Title><Text type="secondary">所有标签完整复用场景替换功能、模型、自动重试与扩图设置</Text></div><Space wrap><Text>全局并发</Text><InputNumber min={1} max={12} value={concurrency} onChange={(value) => setConcurrency(value || 1)} /><Button icon={<RocketOutlined />} onClick={() => void open()}>保存批次并打开全部标签</Button><Button type="primary" disabled={!activeBatch} onClick={startAll}>一键开始所有替换</Button>{totals.failed > 0 && <Button icon={<ReloadOutlined />} onClick={retryAllFailed}>一键重试所有失败</Button>}{activeBatch && totals.total > totals.completed && <Button danger icon={<StopOutlined />} onClick={stopAll}>一键停止全部</Button>}<Button disabled={!activeBatch} onClick={disableCloseWarnings}>解除全部标签关闭提醒</Button><Button icon={<DownloadOutlined />} disabled={!downloadable.length} onClick={() => void downloadAll()}>下载全部（{downloadable.length}）</Button></Space></Flex>{totals.total > 0 && <><Flex gap={24}><Statistic title="任务总数" value={totals.total} /><Statistic title="已完成" value={totals.completed} /><Statistic title="失败" value={totals.failed} /></Flex><Progress percent={Math.round(totals.completed / totals.total * 100)} /></>}</Card>
    <Modal title="选择要导入的图片目录" open={pendingFolderFiles.length > 0} width={980} okText={`导入已选 ${checkedFolderKeys.length} 个目录`} cancelText="取消" okButtonProps={{ disabled: !checkedFolderKeys.length }} onOk={importCheckedFolderFiles} onCancel={() => { setPendingFolderFiles([]); setCheckedFolderKeys([]); }}>
      <Alert type="info" showIcon title="保留完整目录结构，仅选择最深层图片文件夹" description="父级目录只展示结构，不显示图片也不会被导入；叶子目录可以独立勾选，一个目录对应一个工作标签。" style={{ marginBottom: 14 }} />
      <Flex justify="space-between" align="center" style={{ marginBottom: 12 }}><Text type="secondary">已选择 {checkedFolderKeys.length} / {leafFolderKeys.length} 个最深层目录</Text><Space><Button size="small" onClick={() => setCheckedFolderKeys(leafFolderKeys)}>全选</Button><Button size="small" onClick={() => setCheckedFolderKeys([])}>取消全选</Button></Space></Flex>
      <div className="scene-folder-picker-tree" style={{ maxHeight: '58vh', overflowY: 'auto', paddingRight: 8 }}>{renderPickerTree(pendingTree)}</div>
    </Modal>
    <Modal title={selectedGroup ? `${selectedGroup.name} · 图片管理` : '图片管理'} open={Boolean(selectedGroup)} width={900} footer={<Button onClick={() => setSelectedGroupId(undefined)}>完成</Button>} onCancel={() => setSelectedGroupId(undefined)}>{selectedGroup && <><Flex justify="space-between" align="center" wrap gap={12} style={{ marginBottom: 14 }}><Text type="secondary">{selectedGroup.path} · 当前 {selectedGroup.files.length} 张</Text><Upload multiple showUploadList={false} accept="image/png,image/jpeg,image/webp" beforeUpload={(file) => addGroupFile(selectedGroup.id, file as File)}><Button type="primary" icon={<PlusOutlined />}>添加图片</Button></Upload></Flex><Image.PreviewGroup><div className="batch-asset-grid">{selectedGroup.files.map((file, index) => <FileThumbnail key={`${file.name}-${file.size}-${index}`} file={file} onRemove={() => removeGroupFile(selectedGroup.id, file)} />)}</div></Image.PreviewGroup></>}</Modal>
  </div>;
}
